add target to make redhat release
redhat-developer/jenkins-old-community-operator pull request #31
Opened 2020-06-15 17:19 UTC by jkhelil

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes tests (if functionality changed/added)
- [ ] Includes docs (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more details._

## Reviewer Notes

If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than 50% of the OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

2020-06-15 17:27 UTC, waveywaves commented
Can we add the changes to dockerfile in the openshift-ci directory instead of the build directory, it's better that way. This is to avoid any conflicts in the future.

2020-06-16 11:39 UTC, waveywaves requested changes

2020-06-16 11:39 UTC, waveywaves commented on Makefile
> +RH_JENKINS_OPERATOR_VERSION = 0.4.1-rc1
Maybe we should get the latest git tag over here. The process could be to git tag it then run this to get nad build with the latest tag.

2020-06-16 13:26 UTC, akram commented on openshift-ci/Dockerfile.rhel
> +LABEL maintainer "Devtools <devtools@redhat.com>"
Has to be changed:
OpenShift Jenkins Team <openshift-dev-services+jenkins@redhat.com>

2020-06-16 13:26 UTC, akram commented on openshift-ci/Dockerfile.rhel
> +LABEL author "jawed khelil <jkhelil@redhat.com>"
I suggest you to move this also.

2020-06-16 13:26 UTC, akram commented on openshift-ci/Dockerfile.build_image
>  ENV GIT_COMMITTER_NAME OpenShift Developer Sevices
can  you fix this typo?
Services instead of Sevices

2020-06-16 13:26 UTC, akram commented on OPENSHIFT_RELEASE.md
> +- make olm-image-build
can you use back-quotes to put code inside

```
make olm-image-build 
```

2020-06-16 13:59 UTC, jkhelil commented on Makefile
> +RH_JENKINS_OPERATOR_VERSION = 0.4.1-rc1
fixed

2020-06-16 14:00 UTC, jkhelil commented on openshift-ci/Dockerfile.rhel
> +LABEL author "jawed khelil <jkhelil@redhat.com>"
fixed

2020-06-17 06:15 UTC, waveywaves requested changes
Optimization for Dockerfile

2020-06-17 06:15 UTC, waveywaves commented on openshift-ci/Dockerfile.build_image
> +RUN curl -Lo operator-sdk $OPERATOR_SDK_DOWNLOAD_SITE/$OPERATOR_SDK_VERSION/$OPERATOR_SDK_DIST && chmod +x operator-sdk && mv operator-sdk $GOPATH/bin/
Group these commands together ? 
```
RUN mkdir -p $GOPATH/bin ${GOPATH}/src/${GO_PACKAGE_PATH}/ && curl -Lo operator-sdk $OPERATOR_SDK_DOWNLOAD_SITE/$OPERATOR_SDK_VERSION/$OPERATOR_SDK_DIST && chmod +x operator-sdk && mv operator-sdk $GOPATH/bin/
```

2020-06-17 06:15 UTC, waveywaves commented on openshift-ci/Dockerfile.build_image
> +COPY gen-crd-api-config.json .
These can be grouped together in one layer. https://stackoverflow.com/questions/30256386/how-to-copy-multiple-files-in-one-layer-using-a-dockerfile

2020-06-17 06:15 UTC, waveywaves commented on openshift-ci/Dockerfile.build_image
> +RUN make build
Group these together.

2020-06-17 07:18 UTC, jkhelil commented on openshift-ci/Dockerfile.build_image
> +RUN curl -Lo operator-sdk $OPERATOR_SDK_DOWNLOAD_SITE/$OPERATOR_SDK_VERSION/$OPERATOR_SDK_DIST && chmod +x operator-sdk && mv operator-sdk $GOPATH/bin/
I already grouped for operator-sdk install, lets keep it like this, it is more readable and grouping will not add much optimization

2020-06-17 07:20 UTC, jkhelil commented on openshift-ci/Dockerfile.build_image
> +COPY gen-crd-api-config.json .
If you want to copy multiple directories (not their contents) under a destination directory in a single command, you'll need to set up the build context so that your source directories are under a common parent and then COPY that parent.

If you have multiple Dockerfile steps that use different files from your context, COPY them individually, rather than all at once. This ensures that each step’s build cache is only invalidated (forcing the step to be re-run) if the specifically required files change.

2020-06-17 07:20 UTC, jkhelil commented on openshift-ci/Dockerfile.build_image
> +RUN make build
same here, lets separate concerns

2020-06-17 13:57 UTC, merged