[WIP]Rework casc
redhat-developer/jenkins-old-community-operator pull request #74
Opened 2020-09-17 07:36 UTC by jkhelil

2020-09-29 13:25 UTC, akram requested changes

2020-09-29 13:25 UTC, akram commented on chart/jenkins-operator/values.yaml
> +  image: quay.io/jkhelil/openshift-jenkins-operator:0.4.1-cae3b6d5
needs to be changed

2020-09-29 13:25 UTC, akram commented on deploy/crds/openshift_jenkins_v1alpha2_jenkins_cr.yaml
> +      image: 'image-registry.openshift-image-registry.svc:5000/jawed/jenkins-job-dsl:latest'
need to be changed also

2020-09-29 13:25 UTC, akram commented on pkg/apis/jenkins/v1alpha2/jenkins_types.go
> +type SecretRef struct {
wdyt if we rename it to: `SecretName` ?
just like in `pod` there is `serviceAccountName`

2020-09-29 13:25 UTC, akram commented on pkg/apis/jenkins/v1alpha2/jenkins_types.go
> +type ConfigMapRef struct {
same question here:
wdyt if we rename it to: `ConfigMapName` ?
just like in `pod` there is `configMapName`

2020-09-29 13:25 UTC, akram commented on pkg/apis/jenkins/v1alpha2/jenkins_types.go
> +type Customization struct {
What about juste naming it `Configuration` instead of `Customization` ?

2020-09-29 13:25 UTC, akram commented on pkg/configuration/base/resources/meta.go
> +func AddLabelToWatchedCMs(crName, namespace string, k8sClient k8s.Client, configmaps []v1alpha2.ConfigMapRef) error {
better to avoid abbreviations:
use `AddLabelToWatchedConfigMaps` instead of `AddLabelToWatchedCMs`

2020-09-29 13:25 UTC, akram commented on pkg/configuration/base/resources/pod.go
> +	JenkinsSCConfigLabelValue      = "%s-jenkins-config"
Same here, better to avoir abbreviations:
use `JenkinsSidecarConfig*`  or even `JenkinsSidecarContainerConfig*` instead of `JenkinsSCConfig*`

2020-09-29 13:25 UTC, akram commented on pkg/configuration/base/resources/pod.go
> +func NewJenkinsSCConfigContainer(jenkins *v1alpha2.Jenkins) corev1.Container {
Same remark for `SidecarContainer`

2020-09-29 13:25 UTC, akram commented on pkg/configuration/base/resources/pod.go
> +		"REQ_RETRY_CONNECT": JenkinsSCConfigReqRetry,
Use constants for key names

2020-09-29 13:25 UTC, akram commented on pkg/configuration/base/resources/pod.go
> +			Name:      "jenkins-home",
Use constant

2020-09-29 13:25 UTC, akram commented on pkg/configuration/base/resources/pod.go
> +		Name:            JenkinsSCConfigName,
`JenkinsSidecarConfig*`

2020-09-29 13:25 UTC, akram commented on pkg/controller/jenkins/jenkins_controller.go
> +	/*userConfiguration := user.New(config, jenkinsClient)
delete commented out code

2020-09-29 13:25 UTC, akram commented on pkg/controller/jenkins/jenkins_controller.go
> +			Value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true -Dcasc.reload.token=$(POD_NAME)",
is there any security issue with that?

2020-09-29 13:25 UTC, akram commented on pkg/controller/jenkins/reconciler.go
> +/*func (r *ReconcileJenkins) sendNewUserConfigurationFailedNotification(jenkins *v1alpha2.Jenkins, message string, messages []string) {
to delete

2020-09-29 13:25 UTC, akram commented on pkg/controller/jenkins/reconciler.go
> +/*func (r *ReconcileJenkins) sendNewUserConfigurationCompleteNotification(jenkins *v1alpha2.Jenkins, message string) {
to deleter

2020-09-29 13:25 UTC, akram commented on test/e2e/configuration_test.go
>  		Data: map[string]string{
use constant

2020-09-29 13:25 UTC, akram commented on test/e2e/restorebackup_test.go
> +			ConfigurationAsCode: v1alpha2.Customization{
better to restore the previous code as it was more readable

2020-09-29 14:08 UTC, jkhelil commented on pkg/apis/jenkins/v1alpha2/jenkins_types.go
> +type Customization struct {
sure, doing that

2020-09-29 14:09 UTC, jkhelil commented on pkg/apis/jenkins/v1alpha2/jenkins_types.go
> +type ConfigMapRef struct {
it is an internal type and it may hold attributes other than Name, i wil let it like this

2020-09-29 14:09 UTC, jkhelil commented on pkg/apis/jenkins/v1alpha2/jenkins_types.go
> +type SecretRef struct {
it is an internal type and it may hold attributes other than Name, i wil let it like this

2020-09-29 14:11 UTC, jkhelil commented on pkg/controller/jenkins/jenkins_controller.go
> +			Value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true -Dcasc.reload.token=$(POD_NAME)",
It is secure as secret in kubernetes, if you have access to the server, then to the pod, yo have access to this. Dont think this a matter as it is not exposed

2020-09-29 14:11 UTC, jkhelil commented on pkg/controller/jenkins/reconciler.go
> +/*func (r *ReconcileJenkins) sendNewUserConfigurationFailedNotification(jenkins *v1alpha2.Jenkins, message string, messages []string) {
done

2020-09-30 09:17 UTC, akram commented
/lgtm

2020-09-30 09:18 UTC, waveywaves commented
/lgtm

2020-09-30 09:22 UTC, merged