Fix e2e TestJenkinsPodRestart to be compatible with Deployment
redhat-developer/jenkins-old-community-operator pull request #75
Opened 2020-09-17 16:26 UTC by waveywaves

2020-09-22 08:58 UTC, akram requested changes

2020-09-22 08:58 UTC, akram commented on pkg/configuration/base/deployment.go
> +		r.logger.Info("Jenkins BaseConfiguration Completed after reinitialization")
should we not requeue here then?

2020-09-22 08:58 UTC, akram commented on pkg/controller/jenkins/jenkins_controller.go
> +		if strings.Contains(err.Error(), "Terminating state with DeletionTimestamp") {
we need something more robust than checking error message?

2020-09-22 08:58 UTC, akram commented on test/e2e/jenkins.go
> +func createJenkinsCRForJenkinsPodRestart(t *testing.T, name, namespace string) *v1alpha2.Jenkins {
can you rename it `createSimpleJenkinsCR`?

2020-09-22 08:58 UTC, akram commented on test/e2e/wait.go
> +	retries                     = 60
can you change it back to 30 if relevant?

2020-09-22 08:58 UTC, akram commented on test/e2e/wait.go
> +		if jenkinsPhase != "" {
maybe using `len(jenkinsPhase) != 0`?

2020-09-22 08:58 UTC, akram commented on test/e2e/wait.go
> +			t.Logf("Error while listing Jenkins Pods List : %+v", podList)
also print the error in the log.

2020-09-22 08:58 UTC, akram commented on test/e2e/wait.go
> +func WaitForConditionCompletion(retryInterval time.Duration, retries int, jenkins *v1alpha2.Jenkins, checkCondition checkConditionFunc) (*v1alpha2.Jenkins, error) {
rename to `WaitForCondition`?

2020-09-22 17:36 UTC, waveywaves commented on pkg/configuration/base/deployment.go
> +		r.logger.Info("Jenkins BaseConfiguration Completed after reinitialization")
No we shouldn't because this check is in place to only set the BaseConfigurationCompletedTime only when Phase is Reinitializing. When the Phase is in Reinitializing, that means that the Time is set to null. So before we set the Phase to Completed we have to set this. That's why we are requeing after the Jenkins is updated also.

2020-09-22 17:59 UTC, waveywaves commented on pkg/controller/jenkins/jenkins_controller.go
> +		if strings.Contains(err.Error(), "Terminating state with DeletionTimestamp") {
For now changed to check being done in the function for readable code

2020-09-22 18:03 UTC, akram commented
/lgtm

2020-09-22 20:24 UTC, waveywaves commented
/lgtm

2020-09-23 07:25 UTC, akram commented
/lgtm

2020-09-23 07:35 UTC, akram commented
/override continuous-integration/travis-ci/pr

2020-09-23 07:40 UTC, merged