add docs
redhat-developer/jenkins-old-community-operator pull request #81
Opened 2020-09-30 15:16 UTC by jkhelil

2020-09-30 15:30 UTC, akram commented on docs/README.md
> +The easiest way to deploy, manage and upgrade jenkins on kubernetes.
Jenkins

2020-09-30 15:30 UTC, akram commented on docs/README.md
> +- [Insalling the operator](install.md)
Installing

2020-09-30 15:30 UTC, akram commented on docs/configure.md
> +Wen deploying jenkins via the opertor, you can enable configuration as code for jenkins.
s/jenkins/Jenkins/g

s/opertor/operator/

2020-09-30 15:30 UTC, akram commented on docs/configure.md
> +
This should go in a specific section like: "How it works?"

2020-09-30 15:30 UTC, akram commented on docs/configure.md
> +* enabled: speicifies if the configuration as code will be enabled
use "-" to create a list
and backquotes for formatting

2020-09-30 15:30 UTC, akram commented on docs/configure.md
> +Here is an some example of jenkins configmaps:
Here is an example of jenkins `configMaps`:

2020-09-30 15:30 UTC, akram commented on docs/install.md
> +This guide explains how to install jenkins operaotr.
s/operaotr/operator/g

2020-10-01 03:25 UTC, waveywaves requested changes

2020-10-01 03:25 UTC, waveywaves commented on docs/README.md
> +The easiest way to deploy, manage and upgrade jenkins on kubernetes.
also Kubernetes as these are nouns

2020-10-01 03:25 UTC, waveywaves commented on docs/deploy.md
> +## Deploy a Jenkins to Kubernetes
*Deploy a Jenkins instance to Kubernetes

2020-10-01 03:25 UTC, waveywaves commented on docs/deploy.md
> +## Deploy a Jenkins to openshift
*Deploy a Jenkins instance to Openshift

2020-10-01 03:25 UTC, waveywaves commented on docs/install.md
> +## Configure Jenkins Custom Resource Definition
This can be called "Prerequisites" instead as installing the CRD is a prereq to installing  the operator

2020-10-01 07:40 UTC, merged