clean status conditions
redhat-developer/jenkins-old-community-operator pull request #88
Opened 2020-10-07 15:26 UTC by jkhelil

2020-10-07 15:31 UTC, akram requested changes

2020-10-07 15:31 UTC, akram commented on api/v1alpha2/jenkins_types.go
> +	// +patchMergeKey=type
are we really using these ones? what is it for?

2020-10-07 15:31 UTC, akram commented on config/crd/bases/jenkins.jenkins.io_jenkins.yaml
> +    controller-gen.kubebuilder.io/version: v0.2.5
I think you must upgrade your kubebuilder version

2020-10-07 15:35 UTC, akram commented on controllers/jenkins_controller.go
> +	reconcileInitMessage      = "Initializing HyperConverged cluster"
Please change this to remove any reference to HyperConverged / hco . Replace that with `Jenkins Instance` or `Jenkins Controller` or `Jenkins Server` (Jenkins Master wording being deprecated )

2020-10-07 15:35 UTC, akram commented on controllers/jenkins_controller.go
> +		Type:    ConditionReconcileComplete,
can we rename it to `ReconciliationComplete`?

2020-10-07 15:35 UTC, akram requested changes

2020-10-07 15:35 UTC, akram commented on controllers/jenkins_controller.go
> +func (r *JenkinsReconciler) setInitialConditions(jenkins *v1alpha2.Jenkins) error {
Not sure what it does: why are we rolling all the conditions here ?

2020-10-08 04:20 UTC, waveywaves requested changes

2020-10-08 04:20 UTC, waveywaves commented on config/crd/bases/jenkins.jenkins.io_jenkins.yaml
> +    controller-gen.kubebuilder.io/version: v0.2.5
+1

2020-10-09 08:31 UTC, akram requested changes

2020-10-09 08:31 UTC, akram commented on controllers/jenkins_controller.go
> +
Can you change this to Reconciliation insteand or Reconcile

2020-10-09 08:31 UTC, akram commented on controllers/jenkins_controller.go
> +	ConditionReconcileComplete conditionsv1.ConditionType = "ReconcileComplete"
and this one also

2020-10-09 08:41 UTC, jkhelil commented on api/v1alpha2/jenkins_types.go
> +	// +patchMergeKey=type
yes

2020-10-09 08:41 UTC, jkhelil commented on controllers/jenkins_controller.go
> +		Type:    ConditionReconcileComplete,
this is harmonized with conditionAvailable ext, so we are not useing names

2020-10-09 08:41 UTC, jkhelil commented on controllers/jenkins_controller.go
> +
done

2020-10-09 08:41 UTC, jkhelil commented on controllers/jenkins_controller.go
> +	ConditionReconcileComplete conditionsv1.ConditionType = "ReconcileComplete"
done

2020-10-12 07:00 UTC, merged